config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipient.urls", namespace="recipient")),
    path("", include("message.urls", namespace="message")),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

mailings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import (
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingStatisticsView,
    MailingStopView,
    MailingUpdateView,
    SendMailingView,
    home_view,
)

app_name = MailingsConfig.name

urlpatterns = [
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path(
        "mailing/<int:pk>/",
        cache_page(60)(MailingDetailView.as_view()),
        name="mailing_detail",
    ),
    path("mailing/new/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/edit/", MailingUpdateView.as_view(), name="mailing_edit"),
    path(
        "mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path("", home_view, name="home"),
    path("mailing/<int:pk>/stop", MailingStopView.as_view(), name="mailing_stop"),
    path(
        "mailing/statistics/",
        MailingStatisticsView.as_view(),
        name="mailing_statistics",
    ),
    path("mailing/<int:pk>/send/", SendMailingView.as_view(), name="send_mailing"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import UserBlockView, UserCreateView, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailings:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users-list/", UserListView.as_view(), name="users_list"),
    path(
        "profile/<str:email>/block", view=UserBlockView.as_view(), name="profile-block"
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_request.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/models.py
from django.db import models
from django.utils import timezone

from message.models import Message
from recipient.models import Recipient
from users.models import User


class Mailing(models.Model):
    COMPLETED = "CO"
    CREATED = "CR"
    LAUNCHED = "LA"

    STATUS_CHOICES = {
        COMPLETED: "Завершена",
        CREATED: "Создана",
        LAUNCHED: "Запущена",
    }

    first_dispatch = models.DateTimeField(
        verbose_name="Дата и время первой отправки",
        help_text="yyyy-mm-dd 00:00:00",
        null=True,
        blank=True,
    )
    end_dispatch = models.DateTimeField(
        verbose_name="Дата и время окончания отправки",
        help_text="yyyy-mm-dd 00:00:00",
        null=True,
        blank=True,
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, verbose_name="Статус", default=CREATED
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        verbose_name="Сообщение",
        related_name="message",
    )
    recipients = models.ManyToManyField(
        Recipient, verbose_name="Получатели", related_name="recipients"
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="mailing_owner",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = [
            "status",
            "first_dispatch",
            "message",
        ]
        permissions = [
            ("can_see_all_mailings", "Can see all mailings"),
            ("can_cancel_mailing", "Can cancel mailing"),
        ]

    def __str__(self):
        return self.status


class MailingAttempt(models.Model):
    SUCCESSFULLY = "SU"
    FAILED = "FA"

    STATUS_ATTEMPT_CHOICES = {
        SUCCESSFULLY: "Успешно",
        FAILED: "Не успешно",
    }

    date_attempt = models.DateTimeField(
        verbose_name="Дата и время попытки", help_text="yyyy-mm-dd 00:00:00"
    )
    status = models.CharField(
        max_length=20, choices=STATUS_ATTEMPT_CHOICES, verbose_name="Статус"
    )
    mail_response = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        verbose_name="Рассылка",
        related_name="mailing_attempts",
    )

    class Meta:
        verbose_name = "Попытка"
        verbose_name_plural = "Попытки"
        ordering = [
            "status",
            "date_attempt",
        ]

    def __str__(self):
        return f"{self.date_attempt} - {self.status}"

mailings/forms.py
from django.forms import BooleanField, ModelForm

from mailings.models import Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ["message", "recipients"]

mailings/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from mailings.forms import MailingForm
from mailings.models import Mailing, MailingAttempt
from message.models import Message
from recipient.models import Recipient

from .management.commands.send_message import send_mailing


class MailingListView(ListView):
    model = Mailing
    template_name = "mailing_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        if self.request.user.has_perm("mailings.can_see_all_mailings"):
            return Mailing.objects.all()
        return Mailing.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Manager").exists()
        context["is_manager"] = is_manager
        return context


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = "mailing_detail.html"
    context_object_name = "mailing"


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = "add_mailing.html"
    success_url = reverse_lazy("mailings:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        owner = self.request.user
        form.fields["recipients"].queryset = Recipient.objects.filter(owner=owner)
        form.fields["message"].queryset = Message.objects.filter(owner=owner)
        return form


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "add_mailing.html"
    success_url = reverse_lazy("mailings:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете редактировать рассылки.")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        owner = self.request.user
        form.fields["recipients"].queryset = Recipient.objects.filter(owner=owner)
        form.fields["message"].queryset = Message.objects.filter(owner=owner)
        return form


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    template_name = "mailing_confirm_delete.html"
    success_url = reverse_lazy("mailings:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете удалять рассылки.")


def home_view(request):
    total_mail = Mailing.objects.count()
    active_mail = Mailing.objects.filter(status="LA").count()
    unique_recipients = Recipient.objects.values("email").distinct().count()

    context = {
        "total_mail": total_mail,
        "active_mail": active_mail,
        "unique_recipients": unique_recipients,
    }

    return render(request, "home.html", context)


class MailingStatisticsView(ListView):
    model = Mailing
    template_name = "mailing_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings = Mailing.objects.filter(owner=self.request.user)
        mailing_stats = []
        for mailing in mailings:
            stats = {
                "mailing": mailing,
                "successful_attempts_count": mailing.mailing_attempts.filter(
                    status=MailingAttempt.SUCCESSFULLY
                ).count(),
                "failed_attempts_count": mailing.mailing_attempts.filter(
                    status=MailingAttempt.FAILED
                ).count(),
                "total_sent_messages": mailing.mailing_attempts.count(),
            }
            mailing_stats.append(stats)

        context["mailing_stats"] = mailing_stats
        return context


class SendMailingView(View):
    def post(self, request, *args, **kwargs):
        mailing_id = kwargs.get("pk")
        mailing = Mailing.objects.get(pk=mailing_id)

        try:
            send_mailing(mailing)
            messages.success(request, "Рассылка успешно отправлена!")
        except Exception as e:
            messages.error(request, f"Ошибка при отправке рассылки: {str(e)}")

        return HttpResponseRedirect(reverse("mailings:mailing_list"))


class MailingStopView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        user = request.user
        is_manager = user.groups.filter(name="Manager").exists()
        if is_manager or user == mailing.owner:
            mailing.status = "CO"
            mailing.save()

            return redirect("mailings:mailing_list")
        return HttpResponseForbidden("У вас нет прав для отключения рассылки")


def mailing_list_view(request):
    mailings = Mailing.objects.filter(owner=request.user)
    return render(request, "mailing_statistics.html", {"mailings": mailings})

mailings/templates/add_mailing.html
{% extends 'base.html' %}
{% block content %}
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 pt-md-5 pb-md-4 font-weight-normal">Добавить новую рассылку</h4>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
      </form>
      <a href="{% url 'mailings:mailing_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project_3</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <style>
        .card-img-top {
            width: 100%;
            height: 200px;
            object-fit: scale-down;
}
    </style>
</head>
<body>

{% include 'includes/inc_menu.html' %}

{% block content %}

{% endblock %}


<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    </footer>
</div>
<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailings/templates/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

  <p class="lead pt-md-5 pb-md-4">Сервис рассылок - здесь Вы можете настроить свои рассылки.</p>

</div>
<body>
    <h1>Статистика рассылок</h1>
    <p>Всего рассылок: <strong>{{ total_mail }}</strong></p>
    <p>Активные рассылки: <strong>{{ active_mail }}</strong></p>
    <p>Уникальные получатели: <strong>{{ unique_recipients }}</strong></p>
</body>
</html>
{% endblock %}

mailings/templates/mailing_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center"></div>
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Удалить рассылкy</h4>
        <p>Вы уверены, что хотите удалить "{{ mailing.message }}"?</p>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-3">Удалить</button>
      </form>
      <a href="{% url 'mailings:mailing_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailing_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ mailing.message }}</h5>
                    <p class="card-text">Дата и время первой отправки: {{ mailing.first_dispatch }}</p>
                    <p class="card-text">Получатели:</p>
                    <ul>
                        {% for recipient in mailing.recipients.all %}
                            <li>{{ recipient.email }}</li>
                        {% empty %}
                            <li>Нет получателей</li>
                        {% endfor %}
                    </ul>
                    <p class="card-text">Владелец: {{ mailing.owner }}</p>
                    <a href="{% url 'mailings:mailing_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailing_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

  <p class="lead pt-md-5 pb-md-4">Сервис рассылок - здесь Вы можете настроить свои рассылки.</p>

</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for mailing in mailings %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ mailing.message }} / {{ mailing.first_dispatch }}</h5>
                    <p class="card-text">Статус: {{ mailing.status }}</p>
                    {% if mailing.owner == user or is_manager %}
                    {% if mailing.status != "CO" %}
                    <form action="{% url 'mailings:mailing_stop' mailing.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger btn-sm">Отключить рассылку</button>
                    </form>
                    {% endif %}
                    {% endif %}
                    {% if mailing.owner == user %}
                    <form action="{% url 'mailings:send_mailing' mailing.pk %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary">Разослать вручную</button>
                    </form>
                    {% endif %}
                    <a href="{% url 'mailings:mailing_detail' mailing.pk %}"
                       class="btn btn-outline-primary">Подробнее</a>
                    <a href="{% url 'mailings:mailing_edit' mailing.pk %}" class="btn btn-outline-secondary ml-3">Редактировать</a>
                    <a href="{% url 'mailings:mailing_delete' mailing.pk %}"
                       class="btn btn-outline-danger ml-1">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

mailings/templates/mailing_statistics.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

  <p class="lead pt-md-5 pb-md-4">Сервис рассылок - здесь Вы можете настроить свои рассылки.</p>
    <p class="lead pt-md-5 pb-md-4">Статистика рассылок.</p>

</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for stat in mailing_stats %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    {% if stat.mailing.owner == user %}
                    <p class="card-text">Сообщение: {{ stat.mailing.message }}</p>
                    <p class="card-text">Статус: {{ stat.mailing.get_status_display }}</p>
                    <p class="card-text">Успешные попытки: {{ stat.successful_attempts_count }}</p>
                    <p class="card-text">Неуспешные попытки: {{ stat.failed_attempts_count }}</p>
                    <p class="card-text">Всего отправленных сообщений: {{ stat.total_sent_messages }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p>Нет доступных рассылок.</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}