config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipient.urls", namespace="recipient")),
    path("", include("message.urls", namespace="message")),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

recipient/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from recipient.apps import RecipientConfig
from recipient.views import (
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
)

app_name = RecipientConfig.name

urlpatterns = [
    path("recipient/", RecipientListView.as_view(), name="recipient_list"),
    path("recipient/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipient/new/", RecipientCreateView.as_view(), name="recipient_create"),
    path(
        "recipient/<int:pk>/edit/", RecipientUpdateView.as_view(), name="recipient_edit"
    ),
    path(
        "recipient/<int:pk>/delete/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import UserBlockView, UserCreateView, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailings:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users-list/", UserListView.as_view(), name="users_list"),
    path(
        "profile/<str:email>/block", view=UserBlockView.as_view(), name="profile-block"
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_request.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipient/models.py
from django.db import models

from users.models import User


class Recipient(models.Model):
    email = models.CharField(max_length=50, unique=True, verbose_name="Email")
    full_name = models.CharField(max_length=150, verbose_name="Ф.И.О.")
    comment = models.TextField(verbose_name="Комментарий")
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recipients_owner",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = ["full_name"]
        permissions = [
            ("can_see_all_recipients", "Can see all recipients"),
        ]

    def __str__(self):
        return self.full_name

recipient/forms.py
from django.forms import BooleanField, ModelForm

from recipient.models import Recipient


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class RecipientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Recipient
        fields = "__all__"
        exclude = ["owner"]

recipient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from recipient.forms import RecipientForm
from recipient.models import Recipient


class RecipientListView(ListView):
    model = Recipient
    template_name = "recipient_list.html"
    context_object_name = "recipients"

    def get_queryset(self):
        if self.request.user.has_perm("mailings.can_see_all_recipients"):
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=self.request.user)


class RecipientDetailView(LoginRequiredMixin, DetailView):
    model = Recipient
    template_name = "recipient_detail.html"
    context_object_name = "recipient"


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "add_recipient.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "add_recipient.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете редактировать получателя рассылки.")


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    template_name = "recipient_confirm_delete.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете удалять получателя рассылки.")

recipient/templates/add_recipient.html
{% extends 'base.html' %}
{% block content %}
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 pt-md-5 pb-md-4 font-weight-normal">Добавить нового получателя</h4>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
      </form>
      <a href="{% url 'recipient:recipient_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

recipient/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project_3</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <style>
        .card-img-top {
            width: 100%;
            height: 200px;
            object-fit: scale-down;
}
    </style>
</head>
<body>
<div class="container pt-md-5 pb-md-4">
        {% if messages %}
            <ul class="messages">
                {% for msg in messages %}
                    <li {% if msg.tags %} class="{{ msg.tags }}"{% endif %}>{{ msg }}</li>
                {% endfor %}
            </ul>
        {% endif %}

{% include 'includes/inc_menu.html' %}

{% block content %}

{% endblock %}


<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    </footer>
</div>
<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

recipient/templates/recipient_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center"></div>
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Удалить получателя рассылки</h4>
        <p>Вы уверены, что хотите удалить "{{ recipient.full_name }}"?</p>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-3">Удалить</button>
      </form>
      <a href="{% url 'recipient:recipient_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

recipient/templates/recipient_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ recipient.full_name }}</h5>
                    <p class="card-text">Электронная почта: {{ recipient.email }}</p>
                    <p class="card-text">Комментарий: {{ recipient.comment }}</p>
                    <a href="{% url 'recipient:recipient_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipient/templates/recipient_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

  <p class="lead pt-md-5 pb-md-4">Сервис рассылок - здесь Вы можете настроить свои рассылки.</p>

</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for recipient in recipients %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ recipient.full_name }}</h5>
                    <a href="{% url 'recipient:recipient_detail' recipient.pk %}" class="btn btn-primary">Подробнее</a>
                    <a href="{% url 'recipient:recipient_edit' recipient.pk %}" class="btn btn-sm btn-secondary ml-3">Редактировать</a>
                    <a href="{% url 'recipient:recipient_delete' recipient.pk %}" class="btn btn-sm btn-danger ml-1">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}