config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipient.urls", namespace="recipient")),
    path("", include("message.urls", namespace="message")),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

recipient/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from recipient.apps import RecipientConfig
from recipient.views import (
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
)

app_name = RecipientConfig.name

urlpatterns = [
    path("recipient/", RecipientListView.as_view(), name="recipient_list"),
    path("recipient/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipient/new/", RecipientCreateView.as_view(), name="recipient_create"),
    path(
        "recipient/<int:pk>/edit/", RecipientUpdateView.as_view(), name="recipient_edit"
    ),
    path(
        "recipient/<int:pk>/delete/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import UserBlockView, UserCreateView, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailings:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users-list/", UserListView.as_view(), name="users_list"),
    path(
        "profile/<str:email>/block", view=UserBlockView.as_view(), name="profile-block"
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_request.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipient/models.py
from django.db import models

from users.models import User


class Recipient(models.Model):
    email = models.CharField(max_length=50, unique=True, verbose_name="Email")
    full_name = models.CharField(max_length=150, verbose_name="Ф.И.О.")
    comment = models.TextField(verbose_name="Комментарий")
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recipients_owner",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = ["full_name"]
        permissions = [
            ("can_see_all_recipients", "Can see all recipients"),
        ]

    def __str__(self):
        return self.full_name

recipient/forms.py
from django.forms import BooleanField, ModelForm

from recipient.models import Recipient


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class RecipientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Recipient
        fields = "__all__"
        exclude = ["owner"]

recipient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from recipient.forms import RecipientForm
from recipient.models import Recipient


class RecipientListView(ListView):
    model = Recipient
    template_name = "recipient_list.html"
    context_object_name = "recipients"

    def get_queryset(self):
        if self.request.user.has_perm("mailings.can_see_all_recipients"):
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=self.request.user)


class RecipientDetailView(LoginRequiredMixin, DetailView):
    model = Recipient
    template_name = "recipient_detail.html"
    context_object_name = "recipient"


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "add_recipient.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "add_recipient.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете редактировать получателя рассылки.")


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    template_name = "recipient_confirm_delete.html"
    success_url = reverse_lazy("recipient:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете удалять получателя рассылки.")

recipient/templates/includes/inc_menu.html
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Сервис рассылок</a>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Главная</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href='/recipient/'>Клиенты</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href='/recipient/new/'>Добавить клиента</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="/message/">Сообщения</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href='/message/new/'>Добавить сообщение</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="/mailing/">Рассылки</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="/mailing/new/">Добавить рассылку</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if perms.users.can_see_all_users %}
          <a class="nav-link" href="{% url 'users:users_list' %}">Пользователи</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="/mailing/statistics/">Статистика</a>
          {% endif %}
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Авторизация</a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
            <li>
              <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Выход
                </button>
              </form>
            </li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Вход</a></li>
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>