config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipient.urls", namespace="recipient")),
    path("", include("message.urls", namespace="message")),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

message/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from message.apps import MessageConfig
from message.views import (
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
)

app_name = MessageConfig.name

urlpatterns = [
    path("message/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("message/new/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/edit/", MessageUpdateView.as_view(), name="message_edit"),
    path(
        "message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import UserBlockView, UserCreateView, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailings:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users-list/", UserListView.as_view(), name="users_list"),
    path(
        "profile/<str:email>/block", view=UserBlockView.as_view(), name="profile-block"
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_request.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/models.py
from django.db import models

from users.models import User


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name="Тема письма")
    body = models.TextField(verbose_name="Тело письма")
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="message_owner",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["subject"]

    def __str__(self):
        return self.subject

message/forms.py
from django.forms import BooleanField, ModelForm

from message.models import Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ["owner"]

message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from message.forms import MessageForm
from message.models import Message


class MessageListView(ListView):
    model = Message
    template_name = "message_list.html"
    context_object_name = "mail_messages"


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = "message_detail.html"
    context_object_name = "message"


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = "add_message.html"
    success_url = reverse_lazy("message:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = "add_message.html"
    success_url = reverse_lazy("message:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете редактировать сообщения.")


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = "message_confirm_delete.html"
    success_url = reverse_lazy("message:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете удалять сообщения.")

message/templates/add_message.html
{% extends 'base.html' %}
{% block content %}
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 pt-md-5 pb-md-4 font-weight-normal">Добавить новое сообщение</h4>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
      </form>
      <a href="{% url 'message:message_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

message/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project_3</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <style>
        .card-img-top {
            width: 100%;
            height: 200px;
            object-fit: scale-down;
}
    </style>
</head>
<body>

{% include 'includes/inc_menu.html' %}

{% block content %}

{% endblock %}


<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    </footer>
</div>
<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

message/templates/message_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center"></div>
<div class="col-lg-3 col-md-6 col-sm-12 mx-auto text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Удалить сообщение рассылки</h4>
        <p>Вы уверены, что хотите удалить "{{ message.subject }}"?</p>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-3">Удалить</button>
      </form>
      <a href="{% url 'message:message_list' %}" class="btn btn-secondary mb-3">Назад</a>
    </div>
  </div>
</div>
{% endblock %}

message/templates/message_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ message.subject }}</h5>
                    <p class="card-text">Текст письма: {{ message.body }}</p>
                    <p class="card-text">Владелец: {{ message.owner }}</p>
                    <a href="{% url 'message:message_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

message/templates/message_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

  <p class="lead pt-md-5 pb-md-4">Сервис рассылок - здесь Вы можете настроить свои рассылки.</p>

</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for message in mail_messages %}
            {% if message.owner == user %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">{{ message.subject }}</h5>
                        <a href="{% url 'message:message_detail' message.pk %}" class="btn btn-outline-primary">Подробнее</a>
                        <a href="{% url 'message:message_edit' message.pk %}" class="btn btn-outline-secondary ml-3">Редактировать</a>
                        <a href="{% url 'message:message_delete' message.pk %}" class="btn btn-outline-danger ml-1">Удалить</a>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}